### ISSUE TITLE
BUG: Sorry, but you are looking for something that isn't here.

### ISSUE THREAD

**Issue by phyve** [not-only-code/qtranslate-slug#34] opened 2013-03-21 07:07 UTC
**\* updated ***
I get this warning only on 3 pages, the rest of the site works. 
1. The error occurs, when I go to edit a previously created page (before this plugin was installed)
2. Edit an image within the content. 
3. Try to add a title to the image via wordpress
4. As a result the pages stops functioning and I get the above error.

If I disable the plugin, the page works works again.

http://bit.ly/ZAFR2w - this page worked before editing the image (today) that was added to the content previously.

**\* updated ***

I get this warning only on 2 specific pages, the rest of the site works.

If I turn off the plugin, this message no longer appears, but the issues I installed the plugin for  return (which the plugin fixed).

I wish I could give you more information, but I still haven't figured out what is the issues with these pages.

I've changed the permalink structure then changed back to update the links, I've tried recreating the page, but the recreated page still has the same problem.

If I create a new page, the problem does not exist.

reference:

http://bit.ly/Y0Lfxb

Any idea on what the issue might be? I think it is related to the images that are supposed to appear on the page.

**Comment by not-only-code** [comment] 2013-03-21 15:21
Try to delete trashed pages

**Comment by phyve** [comment] 2013-03-21 15:28
I don't have any trashed pages to delete.

**Comment by not-only-code** [comment] 2013-03-21 15:32
What kind of message appears? Can you be more explicit?

**Comment by phyve** [comment] 2013-03-21 15:40
**\* updated ***
I get this warning only on 3 pages, the rest of the site works.

The error occurs, when I go to edit a previously created page (before this plugin was installed)
Edit an image within the content.
Try to add a title to the image via wordpress
As a result the pages stops functioning and I get the above error.
If I disable the plugin, the page works works again.

http://bit.ly/ZAFR2w - this page worked before editing the image (today) that was added to the content previously.

**\* updated ***

Please see attached.
![error](https://f.cloud.github.com/assets/3928279/286475/a1a8c6e0-923d-11e2-9ad8-94c7eaae259e.jpg)

**Comment by not-only-code** [comment] 2013-03-21 15:43
The page **about us** has different slug permalink for both languages, english and french ?

**Comment by phyve** [comment] 2013-03-21 15:58
No, its redirecting the home page by default because it can't find the original page.

**Comment by LC43** [comment] 2013-03-21 15:58
my two cents: have a look at the mysql tables for the slugs, i remember
sometimes they aren't removed even if the post is trashed and then deleted.

**Comment by phyve** [comment] 2013-03-21 16:04
Thanks verde, but I don't think this is a slug deletion issue.

Every page where I've tried updating an image title can no longer be.

When I posted I had 2 pages now I have 4 pages that come up with the same error.

**Comment by not-only-code** [comment] 2013-03-21 16:25
If you delete the images in the editor, the problem persist?
Try to remove completely the attachments to this page..  and try again... maybe is a attachment permalink conflict...

**Comment by phyve** [comment] 2013-03-21 16:45
Yes the problem is still existent.

If I turn off the plugin all the pages appear.

**Comment by not-only-code** [comment] 2013-03-21 16:48
I'm sorry but I can not figure out where the problem is with the information you exhibit here...

**Comment by phyve** [comment] 2013-03-21 17:33
you and me both my friend

**Comment by kuchenundkakao** [comment] 2013-03-21 17:50
Maybe we could get more info if you would do this before the loop:
global $wp_query;
var_dump($wp_query);

Kuchenundkakao

**Comment by not-only-code** [comment] 2013-03-21 17:59
I remember this [solution](https://github.com/not-only-code/qtranslate-slug/issues/31) @kuchenundkakao proposed there.

Recently another user [warned in wordpress forums](http://wordpress.org/support/topic/a-small-bug-with-big-influence) about the same bug.

**Comment by phyve** [comment] 2013-03-21 18:23
I added the code. 

http://bit.ly/ZAFR2w

(Is that what you mean?)

**Comment by kuchenundkakao** [comment] 2013-03-21 20:35
OK, that gives us a bit of information.

$wp_query seems to get messed up on these pages. you can see that on the pages which are not found, it tries to find an attachment named "meet-the-team" opposed to a post. 

Try to apply this (as not-only-code said) https://github.com/not-only-code/qtranslate-slug/issues/31

**Comment by phyve** [comment] 2013-03-21 22:03
Still seem to be having the same problem, didn't remedy anything after adding the code you linked in the last post.

**Comment by kuchenundkakao** [comment] 2013-03-22 13:18
Hmmmm... i'm fresh out of time & ideas…
Does it work if you delete the images again out of the page?

**Comment by LC43** [comment] 2013-03-22 13:56
also, you can print the query between html comments so it doesn't break
your layout

<?php global $wp_query;
 echo "";
?>

**Comment by phyve** [comment] 2013-03-22 16:56
I think I figured out where the issue happens.

These pages are having issues because they have a Parent Page.

I created a page, copied the content from the malfunctioning page and it worked.

I realized I forgot to put it under the parent page and when I did, it gave "Sorry, ..." message. When I removed it from under the parent page it worked.

ANOTHER Note.

I have not placed those pages in the trash, but my custom menu is still pointing to them... And the are now working since I have trashed them. (I haven't updated the menu).

Any thoughts, I think this helps identify exactly where to look.

**Comment by LC43** [comment] 2013-03-22 16:57
Dont you have working pages that have parents?

**Comment by phyve** [comment] 2013-03-22 16:58
I do, but they were never edited after installing the qtranslate-slug plugin.

**Comment by phyve** [comment] 2013-03-22 16:59
I said not place those pages in the trash.

I mean I have NOW placed the original pages in the trash and now they work.

**Comment by not-only-code** [comment] 2013-03-22 17:01
And... if you remove this pages from the trash ?

**Comment by phyve** [comment] 2013-03-22 17:10
Hmmm

After restoring, they all worked except one. "Meet our Team"

**Comment by not-only-code** [comment] 2013-03-22 17:11
I think there is a conflict with trashed, non trashed posts with the same permalink... the first comment i posted in this issue...

**Comment by phyve** [comment] 2013-03-22 17:13
None of my pages share the same permalink though.

Unless I am misunderstanding.

**Comment by LC43** [comment] 2013-03-22 17:14
if you change the permalink of "Meet our team" to a completely new slug,
does it work?

**Comment by phyve** [comment] 2013-03-22 17:16
Before today, I had nothing in the trash.

Changing the slug doesn't work

**Comment by phyve** [comment] 2013-03-22 18:47
Conclusion:

Well I don't really have one. But I suspect the code snippet you guys provided definitely helped. I can at least recreate the pages those pages that were erroring.

I went back to the custom menu and relink everything to the new pages.

I really appreciate all the help you guys donated to this problem.

Thanks

**Comment by phyve** [comment] 2013-03-22 19:59
Sorry, I  believe I've got to the bottom of the issue.

And its something I touched on before.

Its the Page & Subpages causing the issue.

I thought I had other subpages but I actually don't. The about page is the only subpage. So in order for this to work I have to remove the parent.

There is a bug in switching the permalink for pages with a parent. The Children don't get along.

**Comment by not-only-code** [comment] 2013-04-03 13:41
Today In Wordpress forums a user posted an issue similar than yours:
http://wordpress.org/support/topic/help-notice-undefined-offset-0-1?replies=7#post-4047893

@phyve , check please if you are using 'qtrans_generateLanguageSelectCode' as language switcher...

**Comment by LC43** [comment] 2015-01-11 23:31
going to close this after 1 year. Thanks everyone!

**Closed as completed by LC43** 2015-01-11 23:31 UTC
